prefeiturasp/SME-Prova-Serap-App

lib/controllers/prova.controller.dart
lib/dtos/arquivo_metadata.dto.dart
lib/ioc/dependencias.ioc.dart
lib/models/prova_arquivo.model.dart
lib/models/prova_completa.model.dart
lib/repositories/prova.repository.dart
lib/stores/download.store.dart
lib/stores/prova.store.dart
lib/stores/usuario.store.dart
lib/views/prova/prova.view.dart
lib/widgets/cards/prova_card.widget.dart
pubspec.lock
pubspec.yaml

criado calculo de tempo aproximado de download

---

lib/interceptors/autenticacao.interceptor.dart
lib/ui/views/prova/prova.view.dart
pubspec.yaml

feat: Revisar controles de edição de texto

---

lib/stores/prova.store.dart
lib/stores/prova.view.store.dart
lib/ui/views/login/login.view.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/utils/assets.util.dart

Criado estrutura para voltar na questão e botões para avançar ou finalizar a revisão

feat: Criar função de revisar a resposta (tela de revisão)

---

.github/workflows/ci.yml
.github/workflows/main.yml
Dockerfile.flutter
lib/converters/json_conveter.dart
lib/dependencias.ioc.dart
lib/dtos/prova.response.dto.dart
lib/dtos/questao_resposta.response.dto.dart
lib/enums/prova_status.enum.dart
lib/interceptors/autenticacao.interceptor.dart
lib/interfaces/loggable.interface.dart
lib/main.dart
lib/models/prova_resposta.model.dart
lib/services/api_service.dart
lib/services/download.service.dart
lib/services/rest/prova.service.dart
lib/services/rest/questao_resposta.service.dart
lib/stores/home.store.dart
lib/stores/login.store.dart
lib/stores/prova.store.dart
lib/stores/prova.view.store.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart

Criada função de retorno da tela de resumo para revisar prova mudando botoes e salvando as questões atualizadas
AB#49419

feat: Criar função de salvar a alteração e voltar para a listagem de revisão

---

lib/services/download.service.dart
lib/stores/prova.store.dart
lib/ui/views/prova/resumo_respostas.view.dart

Ajustado ordem da exibição das questões
AB#50118

fix: Ajuste na ordenação das questões

---

.gitignore
ios/Flutter/AppFrameworkInfo.plist
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/contents.xcworkspacedata
lib/stores/home.store.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
pubspec.yaml

- Compilacao ultima versao do iOS
- Correção retorno quando nao a provas na listagem

fix: compilacao ios

---

lib/ui/views/prova/resumo_respostas.view.dart

Ajustado valor que estava dando conflito dentro do aplicativo/site
AB#50172

fix: Não está retornando para a tela inicial

---

lib/ui/widgets/appbar/appbar.widget.dart

Ajustado código responsável por sair da conta e do aplicativo
AB#50268

fix: Ação do botão 'Sair' está retornando para a questão.

---

lib/ui/views/splashscreen/splash_screen.view.dart

Ajustado código responsável por sair da conta e do aplicativo
AB#50308

feat: Apoio

---

lib/enums/tipo_questao.enum.dart
lib/services/api_service.dart
lib/services/download.service.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart

Ajustado passagem de parâmetros de revisão e logica de ordenação das questões
AB#50362

fix: Ação do botão 'Revisar' está direcionando para questões aleatórias.

---

lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart

Melhorada lógica responsavel por verificar as perguntas que não foram marcadas
AB#50420

fix: Não Não está apresentando a quantidade de itens sem respostas corretamente

---

lib/main.dart
lib/stores/prova.store.dart
lib/ui/views/home/home.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/dialog/dialogs.dart

fix:50430 - ajuste para sair do app

---

lib/stores/prova.view.store.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/appbar/appbar.widget.dart

Chama dispose da prova ao sair do app
AB#50498

fix: Não está contabilizando itens de resposta construída como item sem resposta na tela de resumos

---

lib/ui/widgets/dialog/dialog_default.widget.dart

Mudada estrutura do dialog no aplicativo no contexto web
AB#50438

fix: Ajustar widget quando finalizado prova

---

lib/stores/prova.store.dart
lib/ui/widgets/dialog/dialog_default.widget.dart
lib/ui/widgets/dialog/dialogs.dart

Criado Dialog de tempo de prova
Mudado estrutura dos dialogs
Responsividade para tamanho de tela default do windows
Responsividade parar mobile e web
AB#49463

feature: Criar modal de questionamento que o usuário tem um tempo para finalizar a prova

---

lib/stores/prova.view.store.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart

Correção do fluxo de revisão das respostas

Correção do fluxo de respostas

---

lib/stores/prova.store.dart
lib/stores/prova.view.store.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/dialog/dialog_default.widget.dart
lib/ui/widgets/dialog/dialogs.dart

Ajustado logica de mudar valor corretamente do que foi digitado na questão de item construído
Outros ajustes finos na interface

fix: Não esta contabilizando resposta do item construído

---

lib/enums/tempo_status.enum.dart
lib/models/prova_resposta.model.dart
lib/models/tempo_resposta.model.dart
lib/stores/prova.store.dart
lib/stores/prova_resposta.store.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/prova/prova.view.dart
lib/ui/widgets/appbar/appbar.widget.dart

Foi feita a tarefa 50446 onde é necessario enviar para o back os segundos passado na questão

feature:50446

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/orientacao_inicial/orientacao_inicial.view.dart
lib/ui/widgets/appbar/appbar.widget.dart
lib/ui/widgets/dialog/dialogs.dart
pubspec.yaml

Ajuste nas fontes que estavam ultrapassando o tamanho do componente

fix: Ajustar aplicação para que quando aumentado tamanho da fonte não apresente as palavras cortadas.

---

lib/main.dart
lib/ui/views/orientacao_inicial/orientacao_inicial.view.dart
lib/utils/tela_adaptativa.util.dart

Adequação da página de orientações iniciais para dispositivos móveis

feat: Adequar tela de orientações iniciais

---

lib/ui/views/prova/prova.view.dart

Adequação da página de prova para dispositivos móveis

feat: Adequar tela da Prova

---

lib/ui/widgets/appbar/appbar.widget.dart

Corrigindo texto cortando na fonte para dislexia

fix: Ajuste na app bar

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart

Adequação da tela de principal para telas de smartphones

Adequar tela da Área do estudante

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/orientacao_inicial/orientacao_inicial.view.dart

Adequação da tela de principal para telas de smartphones

feat: Adequar tela da Área do estudante

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/widgets/adaptative/adaptative.widget.dart
lib/ui/widgets/buttons/botao_default.widget.dart

tela não estava com os tamanhos corretos

fix: correção tela de listagem de provas

---

lib/database/app.database.dart
lib/managers/download.manager.dart
lib/models/prova.model.dart
lib/stores/prova.store.dart
lib/stores/prova_tempo_exeucao.store.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
pubspec.yaml

fix: correção mensagem de tempo acabando nao apresentada

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/widgets/bases/base_state.widget.dart

[AB#53820](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/53820)

fix: layout web

---

lib/ui/views/home/home.view.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/bases/base_state.widget.dart
lib/ui/widgets/bases/base_stateless.widget.dart

[AB#53820](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/53820)

fix: correção layout web

---

lib/stores/prova_resposta.store.dart
lib/ui/views/prova/prova.view.dart

[AB#54307](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54307)

Fix/54307 - Prova fica travada para o aluno

---

lib/main.ioc.dart
lib/utils/firebase.util.dart
lib/workers/jobs/baixar_prova.job.dart
pubspec.yaml

[AB#54615](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54615)

fix(AB#54615): Correção para o pre download da prova

---

lib/ui/views/orientacao_inicial/orientacao_inicial.view.dart
lib/ui/views/prova/contexto_prova.view.dart
lib/ui/widgets/barras/barra_progresso.widget.dart

[AB#54192](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54192)

fix: centralização das telas de boas vindas e contexto da prova 

---

lib/managers/download.manager.dart
lib/stores/prova.store.dart
lib/ui/views/prova/prova.view.dart

adicionada pausa em todos os downloads caso o aluno inicie uma prova, com a retomada do download automaticamente tão logo finalize a prova;

Pausa nos downloads ao iniciar prova

---

lib/converters/json_conveter.dart
lib/dtos/prova_anterior.response.dto.dart
lib/main.ioc.dart
lib/services/rest/prova.service.dart
lib/stores/home_provas_anteriores.store.dart
lib/ui/views/home/home.view.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart
lib/utils/date.util.dart

[AB#54490](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54490)

User Story 54490: Seção de provas finalizadas

---

lib/database/app.database.dart
lib/dtos/download.response.dto.dart
lib/enums/tipo_dispositivo.enum.dart
lib/main.dart
lib/managers/download.manager.dart
lib/models/prova.model.dart
lib/services/api_service.dart
lib/services/rest/download.service.dart
lib/stores/principal.store.dart
lib/utils/tela_adaptativa.util.dart
lib/workers/jobs/baixar_prova.job.dart
pubspec.lock
pubspec.yaml

[AB#54486](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54486)

User Story 54486: Informação de downloads de provas - P

---

lib/dtos/prova.response.dto.dart
lib/stores/home.store.dart
lib/ui/views/home/home.view.util.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart
lib/ui/widgets/bases/base_tab.widget.dart

[AB#54490](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54490)

fix: visualizar provas finalizadas offline

---

lib/dtos/prova.response.dto.dart
lib/models/prova.model.dart
lib/stores/home.store.dart
lib/stores/prova.store.dart
lib/ui/views/home/home.view.util.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart
lib/ui/widgets/bases/base_tab.widget.dart
lib/workers/jobs/baixar_prova.job.dart

[AB#54490](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54490)

Story/54490 - Provas finalizadas

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart

[AB#55845](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/55845)

Bug 55845: Ajustar para que o texto da situação da prova finalizada seja apresentado completo quando alterado o tamanho da fonte.

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart
lib/ui/views/prova/resumo_respostas.view.dart

[AB#55867](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/55867)

Bug 55867: Sistema não mostra texto com a quantidade correta de questões não respondidas em prova com tempo.

---

lib/stores/prova.store.dart

[AB#56481](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/56481)

fix(AB#56481): prova iniciando com tempo de finalização

---

lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart

[AB#56503](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/56503)

Bug 56503: [54059 Google Analytics] Ajustar cor de fundo dos itens da prova

---

lib/main.route.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/dialog/dialogs.dart

[AB#56516](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/56516)

Bug 56516: [54059 - Google Analytics] Sistema não permiti ação na mensagem quando finalizado e enviado a prova.

---

lib/managers/download.manager.dart
lib/stores/prova.store.dart
lib/stores/usuario.store.dart

[AB#55619](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/55619)

Bug 55619: Sistema não retoma download da prova após finalizar uma prova já baixada.

---

lib/main.ioc.dart
lib/main.route.dart
lib/services/rest/auth.service.dart
lib/stores/login.store.dart
lib/stores/login_adm.store.dart
lib/stores/principal.store.dart
lib/stores/usuario.store.dart
lib/ui/views/login/login.view.dart
lib/ui/views/login/login_adm.view.dart
lib/ui/widgets/appbar/appbar.widget.dart
lib/utils/router.util.dart
pubspec.lock
pubspec.yaml

[AB#51981](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/51981)

User Story 51981: [SERAp Estudantes] Acesso ADM para consulta das provas (Login) - G

---

lib/database/app.database.dart
lib/database/daos/arquivo_video.dao.dart
lib/dtos/prova_detalhes.response.dto.dart
lib/managers/download.manager.dart
lib/models/prova.model.dart
lib/models/questao.model.dart
lib/stores/principal.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/widgets/video_player/video_player.widget.dart
lib/utils/idb/idb_factory.dart
lib/utils/idb/idb_factory_io.dart
lib/utils/idb/idb_factory_unsuported.dart
lib/utils/idb/idb_factory_web.dart
lib/utils/idb_file.util.dart
lib/utils/universal/app.util.dart
lib/utils/universal/universal.util.dart
lib/utils/universal/web.util.dart
pubspec.lock
pubspec.yaml

[AB#53095](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/53095)

Story/53095 - Poc videos

---

web/manifest.json

[AB#54664](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54664)

Bug 54664: Erros no console

---

web/splash/style.css

[AB#54664](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54664)

Fix/54664 - Correção mensagem console 

---

lib/stores/principal.store.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/widgets/audio_player/audio_player.widget.dart

[AB#51188](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/51188)

fix: ajustes do repasse

---

lib/stores/principal.store.dart
lib/utils/universal/app.util.dart
lib/utils/universal/web.util.dart

[AB#57645](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/57645)

Bug 57645: [51188 - Acessibilidade] Sistema não faz logoff ao clicar no botão "Sair".

---

lib/ui/views/prova/resumo_respostas.view.dart

[AB#57677](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/57677)

Bug 57677: [51188 - Acessibilidade] Na tela de resumo da prova não é possível fazer scroll na visão.

---

lib/managers/download.manager.dart

[AB#57679](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/57679)

Bug 57679: [51188 - Acessibilidade] Download da prova pausado via browser.

---

lib/managers/download.manager.dart
pubspec.lock
pubspec.yaml

[AB#54845](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/54845)

Bug 54845: Mensagem "Sem conexão" mesmo quando está conectado

---

lib/ui/widgets/appbar/appbar.widget.dart

[AB#59434](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/59434)

Bug 59434: [55632 - Tratar nome social] - Ajustar apresentação do nome estudante, escola e nome da prova para quando houver aumento da fonte.

---

lib/converters/json_conveter.dart
lib/dtos/autenticacao_dados.response.dto.dart
lib/enums/deficiencia.enum.dart
lib/stores/login.store.dart
lib/stores/usuario.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/splashscreen/splash_screen.view.dart
lib/ui/widgets/bases/base_state.widget.dart
lib/ui/widgets/video_player/video_player.widget.dart
lib/workers/dispacher.dart

[AB#51187](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/51187)

User Story 51187: [SERAp Estudantes] - Acessibilidade telas da Prova - Surdos - G

---

lib/ui/views/admin/prova_resumo.admin.view.dart

[AB#60390](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/60390)

Bug 60390: [55638 Acesso ADM] - Ajustar para que a descrição da coluna 'Visualizar item' seja apresentado corretamente.

---

lib/ui/views/admin/home.admin.view.dart
lib/ui/views/admin/prova_resumo_caderno.admin.view.dart

[AB#60434](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/60434)

fix: correção carregamento web

---

lib/converters/json_conveter.dart
lib/dtos/versao_atualizacao.respose.dto.dart
lib/services/rest/versao.service.dart
lib/ui/views/splashscreen/splash_screen.view.dart
pubspec.lock
pubspec.yaml

[AB#52844](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/52844)

feat: implementação sistema de atualização

---

Jenkinsfile

Pipeline e versão

---

lib/ui/widgets/appbar/appbar.widget.dart

[AB#61752](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/61752)

Bug 61752: [57323 - Acesso ADM] Ajustar nomenclatura do tipo de perfil exibido no SERAp estudantes.

---

lib/database/app.database.dart
lib/dtos/prova.response.dto.dart
lib/dtos/questao_resposta.dto.dart
lib/managers/download.manager.dart
lib/models/prova.model.dart
lib/services/rest/questao_resposta.service.dart
lib/stores/home.store.dart
lib/stores/prova.store.dart
lib/stores/prova_resposta.store.dart
lib/ui/views/prova/prova.view.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/views/splashscreen/splash_screen.view.dart
lib/workers/jobs/baixar_prova.job.dart
lib/workers/jobs/sincronizar_resposta.job.dart
lib/workers/sincronizar_resposta.worker.dart
pubspec.yaml

[AB#61013](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/61013)

User Story 61013: [SERAp Estudantes] Envio das respostas em lote - G

---

lib/converters/json_conveter.dart
lib/interceptors/compressao.interceptor.dart
lib/services/api_service.dart
pubspec.lock
pubspec.yaml

[AB#61003](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/61003)

User Story 61003: [SERAp Estudantes] Compactação da prova - MG

---

lib/ui/views/prova/questao.view.dart
lib/ui/views/splashscreen/splash_screen.view.dart
pubspec.lock

[AB#64507](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/64507)

Bug 64507: [61003 - Compactação da prova] A cor de fundo da tela de itens está divergente da cor padrão das demais telas.

---

lib/ui/views/splashscreen/splash_screen.view.dart
pubspec.lock
pubspec.yaml

[AB#65363](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/65363)

Bug 65363: Informação do IMEI está incorreta

---

lib/converters/json_conveter.dart
lib/database/daos/arquivo.dao.dart
lib/database/daos/arquivo_audio.dao.dart
lib/database/daos/arquivo_video.dao.dart
lib/database/daos/download_prova.dao.dart
lib/dtos/alternativa.response.dto.dart
lib/dtos/arquivo.response.dto.dart
lib/dtos/prova_detalhes.response.dto.dart
lib/dtos/questao_completa.response.dto.dart
lib/interceptors/compressao.interceptor.dart
lib/main.dart
lib/managers/download.manager.store.dart
lib/services/rest/questao.service.dart
pubspec.yaml

[AB#63398](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/63398)

User Story 63398: [SERAp Estudantes] Melhorar requisições do download da prova - G

---

lib/database/app.database.dart
lib/database/daos/resposta_prova.dao.dart
lib/database/tables/questao.table.dart
lib/dtos/questao.response.dto.dart
lib/dtos/questao_completa.response.dto.dart
lib/models/questao.model.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/views/prova/widgets/questao_admin.widget.dart
lib/ui/views/prova/widgets/questao_aluno.widget.dart
pubspec.lock
pubspec.yaml

[AB#65816](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/65816)

Bug 65816: [63398 Melhorar requisições do download da prova] Sistema não faz download quando prova possui itens sem texto base.

---

lib/database/app.database.dart
lib/database/core/mobile.database.dart
lib/database/core/web.database.dart
lib/database/tables/resposta_prova.table.dart
lib/main.dart
lib/managers/download.manager.store.dart
lib/models/resposta_prova.model.dart
lib/stores/prova_resposta.store.dart
lib/ui/widgets/appbar/appbar.widget.dart
lib/utils/app_config.util.dart
lib/utils/string.util.dart
lib/utils/universal/app.util.dart
lib/utils/universal/web.util.dart
pubspec.yaml

[AB#65437](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/65437)

Bug 65437: Esta resetando o tempo de questão ao voltar na questão anterior quando a resposta ainda não foi sincronizada

---

lib/stores/principal.store.dart
lib/utils/app_config.util.dart

[AB#66577](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/66577)

feat(AB#66577): Adicionado comfiguracao da url do SERAp

---

lib/ui/views/prova/questao.view.dart
lib/ui/widgets/video_player/video_player.widget.dart

[AB#65987](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/65987)

User Story 65987: [SERAp Estudantes] Otimizar a exibição de provas com vídeos - P

---

android/app/build.gradle
android/build.gradle
lib/converters/error_converter.dart
lib/interceptors/autenticacao.interceptor.dart
lib/main.dart
lib/managers/download.manager.store.dart
lib/stores/home.store.dart
lib/stores/login.store.dart
lib/stores/login_adm.store.dart
lib/stores/orientacao_inicial.store.dart
lib/stores/principal.store.dart
lib/stores/prova.store.dart
lib/stores/prova_resposta.store.dart
lib/stores/usuario.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/splashscreen/splash_screen.view.dart
lib/ui/widgets/appbar/popup_submenu_item.dart
lib/utils/firebase.util.dart
lib/workers/dispacher.dart
lib/workers/finalizar_prova.worker.dart
lib/workers/jobs/baixar_prova.job.dart
lib/workers/jobs/remover_provas.job.dart
lib/workers/sincronizar_resposta.worker.dart
pubspec.lock
pubspec.yaml

[AB#67911](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/67911)

User Story 67911: [SERAp Estudantes] Crashlytics - PP

---

lib/stores/questao_revisao.store.dart
lib/stores/questao_revisao.store.g.dart
lib/ui/views/prova/resumo_respostas.view.dart

[AB#67758](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/67758)

Bug 67758: Mensagem de prova já finalizada, quando clicado no botão 'Finalizar e enviar' mais de uma vez

---

lib/stores/home.store.dart
lib/stores/login.store.dart
lib/stores/principal.store.dart
lib/stores/principal.store.g.dart
lib/stores/prova.store.dart
lib/stores/prova.store.g.dart
lib/stores/prova_resposta.store.dart
lib/stores/usuario.store.dart
lib/ui/widgets/dialog/dialogs.dart
lib/utils/firebase.util.dart
lib/workers/finalizar_prova.worker.dart
lib/workers/sincronizar_resposta.worker.dart
pubspec.lock
pubspec.yaml

[AB#67476](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/67476)

Bug 67476: Problemas durante execução da prova quando conexão offline

---

lib/stores/principal.store.dart
lib/stores/prova.store.dart
lib/stores/prova.view.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/widgets/appbar/appbar.widget.dart

[AB#67479](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/67479)

Bug 67479: Sistema finaliza prova com tempo automaticamente quando acessado no mesmo dispositivo

---

lib/ui/views/home/home.view.util.dart

[AB#69312](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/69312)

Bug 69312: Prova EJA - Provas indisponíveis no último dia de aplicação

---

lib/stores/prova.view.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/widgets/tempo_execucao.widget.dart
pubspec.yaml

[AB#70455](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70455)

Bug 70455: [69607 - Liberação da versão] - Sistema apresenta tela cinza ao selecionar uma alternativa.

---

lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/prova/questao.view.dart

[AB#70462](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70462)

Bug 70462: [69607 - Liberação da versão] - Sistema exibi contador somente na primeira questão.

---

lib/database/app.database.dart
lib/database/app.database.g.dart
lib/database/tables/prova.table.dart
lib/dtos/prova.response.dto.dart
lib/dtos/prova.response.dto.g.dart
lib/interfaces/loggable.interface.dart
lib/managers/download.manager.store.dart
lib/models/prova.model.dart
lib/models/prova.model.g.dart
lib/stores/home.store.dart
lib/stores/home.store.g.dart
lib/stores/prova.store.dart
lib/stores/prova.store.g.dart
lib/workers/jobs/baixar_prova.job.dart

[AB#70504](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70504)

Bug 70504: [69607 - Liberação da versão] - Troca de caderno do estudante quando dado continuidade da prova em outro dispositivo.

---

lib/database/daos/prova.dao.dart
lib/managers/download.manager.store.dart
lib/services/rest/prova.service.chopper.dart
lib/services/rest/prova.service.dart
lib/stores/prova.store.dart
lib/stores/prova.store.g.dart
lib/workers/jobs/finalizar_prova_pendente.job.dart
pubspec.yaml

[AB#70516](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70516)
[AB#70318](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70318)

fix: correção envio offline e tempo de inicio da prova iniciada offline

---

lib/stores/tema.store.dart
lib/stores/tema.store.g.dart
lib/ui/views/admin/prova_questao.admin.view.dart
lib/ui/views/admin/prova_resumo.admin.view.dart
lib/ui/views/admin/prova_resumo_caderno.admin.view.dart
lib/ui/views/home/home.view.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/appbar/appbar.widget.dart
lib/ui/widgets/bases/base_state.widget.dart

[AB#70605](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70605)

Bug 70605: Ajustar apresentação do nome estudante, escola e nome da prova para quando houver aumento da fonte.

---

lib/ui/views/prova/questao.view.dart

[AB#70607](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/70607)

Bug 70607: Tela de itens no navegador não segue prototipo.

---

lib/database/daos/prova_caderno.dao.dart

[AB#72251](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/72251)

Bug 72251: [67964 - Reaproveitar questões no download] - Resumo da prova não é apresentado.

---

lib/converters/json_conveter.dart
lib/database/core/mobile.database.dart
lib/dtos/data_hora_servidor.response.dto.dart
lib/dtos/data_hora_servidor.response.dto.g.dart
lib/services/api.dart
lib/services/api_service.dart
lib/services/rest/configuracao.service.chopper.dart
lib/services/rest/configuracao.service.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/splashscreen/splash_screen.view.dart
lib/ui/widgets/dialog/dialogs.dart
test/unit/login/login_test.mocks.dart
test/unit/prova_download/prova_download_test.mocks.dart

[AB#72231](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/72231)

User Story 72231: [SERAp Estudantes] Validar data e hora do dispositivo com o servidor - G

---

lib/stores/prova.store.dart
lib/stores/prova_resposta.store.dart

[AB#74390](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/74390)

Bug 74390: [73039 - Gravar respostas em outra pasta do dispositivo] - Não estão sendo excluídas do banco local as respostas da prova.

---

lib/services/rest/versao.service.chopper.dart
lib/services/rest/versao.service.dart
lib/ui/views/splashscreen/splash_screen.view.dart
pubspec.yaml

[AB#74338](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/74338)

fix: correção campo correto para o envio do id do dispositivo

---

lib/database/app.database.dart
lib/database/app.database.g.dart
lib/database/daos/jobs.dao.dart
lib/database/daos/jobs.dao.g.dart
lib/database/daos/resposta_prova.dao.dart
lib/database/tables/jobs.table.dart
lib/enums/job_status.enum.dart
lib/models/job.model.dart
lib/models/job.model.g.dart
lib/ui/views/home/home.view.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/buttons/botao_terceario.widget.dart
lib/ui/widgets/dialog/dialogs.dart
lib/ui/widgets/status_sincronizacao/status_sincronizacao.dialog.dart
lib/ui/widgets/status_sincronizacao/status_sincronizacao.widget.dart
lib/utils/date.util.dart
lib/utils/tema.util.dart
lib/workers/dispacher.dart
lib/workers/jobs/sincronizar_respostas.job.dart
pubspec.yaml

[AB#72848](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/72848)

User Story 72848: [SERAp Estudantes] Apresentar status da sincronização

---

lib/database/core/mobile.database.dart
lib/main.dart
lib/main.ioc.dart
lib/main.isolate.dart
lib/stores/job.store.dart
lib/stores/job.store.g.dart
lib/ui/views/home/home.view.dart
lib/ui/widgets/status_sincronizacao/status_sincronizacao.widget.dart
lib/workers/dispacher.dart
pubspec.yaml
test/unit/prova_download/prova_download_test.dart

[AB#75560](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/75560)

Bug 75560: [72848 - Apresentar status da sincronização] - Não está deixando status na cor verde após sincronização.

---

lib/main.isolate.dart
lib/stores/job.store.dart
lib/workers/dispacher.dart
pubspec.yaml

[AB#75583](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/75583)

Bug 75583: [72848 - Apresentar status da sincronização] - No navegador não é apresentado os dados da ultima sincronização.

---

lib/ui/widgets/adaptative/adaptative.widget.dart
lib/ui/widgets/status_sincronizacao/status_sincronizacao.dialog.dart
pubspec.yaml

[AB#75559](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/75559)

Bug 75559: [72848 - Apresentar status da sincronização] - Ajustar exibição dos dados de sincronização quando aumentado a fonte da aplicação.

---

lib/stores/home.store.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/prova/questao.view.dart
lib/workers/jobs/baixar_prova.job.dart

[AB#74517](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/74517)

Bug 74517: [73039 - Gravar as respostas em outra pasta do dispositivo] - Prova não é finalizada após retomar conexão com a internet

---

lib/interceptors/autenticacao.interceptor.dart
lib/main.ioc.dart
lib/stores/login.store.dart
lib/stores/login_adm.store.dart
lib/stores/principal.store.dart
lib/stores/usuario.store.dart
lib/utils/provas.util.dart
lib/workers/jobs/baixar_prova.job.dart

[AB#66557](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/66557)

Bug 66557: Informações do usuário ADM não aparecem quando atualizado página do SERAp estudantes.

---

.gitignore
lib/database/app.database.dart
lib/main.dart
lib/managers/download.manager.store.dart
lib/stores/login.store.dart
lib/stores/prova.store.dart
lib/stores/usuario.store.dart
lib/ui/views/splashscreen/splash_screen.view.dart
lib/utils/firebase.util.dart
lib/workers/jobs/baixar_prova.job.dart
pubspec.lock
pubspec.yaml
test/widget/login/login.widget_test.dart

[AB#76652](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76652)

Bug 76652: [76016 - Liberação da versão] - Download em background não está funcionando.

---

lib/ui/widgets/appbar/appbar.widget.dart

[AB#76452](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76452)

Bug 76452: [76016 - Liberação da versão] - Mensagem de finalização da prova com tempo para usuário que não iniciou a prova.

---

lib/stores/home.store.dart
lib/stores/prova.store.dart
lib/stores/questao_revisao.store.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/widgets/appbar/appbar.widget.dart
lib/workers/jobs/baixar_prova.job.dart

[AB#76708](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76708)

Bug 76708: [76016 - Liberação da versão] - Sistema está permitindo revisar questões não respondidas quando tempo extra para revisão.

---

lib/ui/views/prova/questao.view.dart

[AB#76891](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76891)

Bug 76891: [76016 - Liberação da versão] - Prova para deficientes visuais não está apresentando os audios durante execução da prova.

---

lib/stores/prova.store.dart
lib/ui/views/prova/prova.media.util.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart

[AB#76805](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76805)

Bug 76805: [76016 - Liberação da versão] - Não é exibido os vídeos na revisão das questões.

---

lib/enums/modalidade.enum.dart
lib/ui/views/admin/home.admin.view.dart

[AB#76906](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76906)

Bug 76906: [76016 - Liberação da versão] - Tela Acesso ADM - Ajustar filtro modalidade para apresentar apenas as modalidades EJA, EF e EM.

---

lib/ui/views/admin/prova_questao.admin.view.dart
lib/ui/views/prova/questao.view.dart
lib/ui/widgets/video_player/video_player.widget.dart

[AB#76795](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/76795)

Bug 76795: [76016 - Liberação da versão] - Sistema apresenta instabilidade ao exibir os vídeos na execução da prova.

---

lib/database/app.database.dart

[AB#77421](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/77421)

fix(AB#77430): correção migration para alteração de estrutura

---

lib/dtos/arquivo.response.dto.dart
lib/ui/views/prova/prova.view.util.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/widgets/questao_admin.widget.dart
lib/ui/views/prova/widgets/questao_aluno.widget.dart
pubspec.lock
pubspec.yaml

[AB#78672](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/78672)

Bug 78672: SERAp estudantes - Erro no console ao tentar revisar uma questão da prova.

---

lib/ui/views/prova/prova.view.util.dart
pubspec.lock
pubspec.yaml

[AB#79381](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/79381)

Bug 79381: Erro ao dar zoom na imagem no Acesso ADM

---

lib/managers/download.manager.store.dart
lib/stores/prova_resposta.store.dart
lib/stores/prova_resposta.store.g.dart
lib/ui/views/prova/prova.view.util.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/views/prova/widgets/questao_aluno.widget.dart
pubspec.lock
pubspec.yaml

[AB#79925](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/79925)

Bug 79925: [76142 - Resultados do aluno] - Sistema não está marcando a resposta em tela.

---

lib/dtos/prova_resultado_resumo.response.dto.dart
lib/dtos/prova_resultado_resumo.response.dto.g.dart
lib/dtos/prova_resultado_resumo_questao.response.dto.dart
lib/dtos/prova_resultado_resumo_questao.response.dto.g.dart
lib/main.route.dart
lib/services/rest/prova_resultado.service.chopper.dart
lib/services/rest/prova_resultado.service.dart
lib/stores/prova_resultado_resumo_view.store.dart
lib/stores/prova_resultado_resumo_view.store.g.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart
lib/ui/views/prova_resultado/prova_resultado_resumo.view.dart
lib/ui/views/prova_resultado/questao_resultado_detalhe.view.dart
lib/ui/widgets/appbar/appbar.widget.dart

[AB#80629](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/80629)

Bug 80629: [76142 - Tela de Resultado] - Erro na exibição das colunas da tabela de questões

---

lib/dtos/questao.response.dto.dart

[AB#80624](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/80624)

Bug 80624: [76145 - Resultado por item] - Não é exibida a questão completa quando visualizado o item no resultado.

---

lib/stores/questao_tai_view.store.dart
lib/ui/views/tai/prova_tai.view.dart
lib/ui/views/tai/questao_tai.view.dart
pubspec.yaml

[AB#81521](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/81521)

Bug 81521: [51191 - TAI - Iniciar a prova] - Ajustar layout da prova.

---

lib/services/rest/prova_tai.service.chopper.dart
lib/services/rest/prova_tai.service.dart
lib/stores/prova_tai.view.store.dart
pubspec.yaml

[AB#81530](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/81530)

Bug 81530: [51191 - TAI - Iniciar prova ] - Ação de "Continuar Prova" quando não tem conexão com R está abrindo a prova normalmente.

---

lib/ui/widgets/video_player/video_player.widget.dart
pubspec.yaml

[AB#83721](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/83721)

Bug 83721: [SERAp Estudantes] Expandir vídeo não permite voltar ao item

---

lib/stores/prova.store.dart
lib/stores/prova_tai.view.store.dart
lib/stores/questao_tai_view.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/splashscreen/splash_screen.view.dart
lib/ui/views/tai/questao_tai.view.dart
lib/ui/views/tai/resumo_tai.view.dart
pubspec.lock
pubspec.yaml

[AB#83708](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/83708)

User Story 83708: [SERAp Estudantes] Não apagar a tela do dispositivo enquanto estiver na prova

---

android/app/build.gradle
pubspec.lock
pubspec.yaml

[AB#85886](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/85886)

User Story 85886: [SERAp Estudantes] Alteração no método de assinatura do apk

---

lib/stores/home.store.dart
pubspec.yaml

[AB#86877](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/86877)

Bug 86877: [83714 - Tabela tipo de deficiencia] - Não apresenta o vídeo da questão quando utilizado mesmo dispositivo para execução da prova.

---

lib/database/app.database.dart
lib/database/app.database.g.dart
lib/database/tables/arquivo_audio.table.dart
lib/database/tables/arquivo_video.table.dart
lib/managers/download.manager.store.dart
lib/utils/app_config.util.dart
pubspec.yaml

[AB#87262](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/87262)

Bug 87262: [SERAp Estudantes] - Não exibe video das questões quando feito download da prova com as mesmas questões contendo áudio.

---

.github/workflows/CI-CD.yml
Jenkinsfile
Jenkinsfile-web

Ajustes CI/CD

---

lib/ui/views/prova/prova.view.util.dart
pubspec.lock
pubspec.yaml

[AB#92367](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/92367)

Bug 92367: [SERAp Estudantes] - Aplicação no dispositivo físico está exibindo as questões com espaço entre o texto base e o enunciado.

---

lib/ui/views/prova/prova.view.util.dart
pubspec.lock
pubspec.yaml

Reverts prefeiturasp/SME-Prova-Serap-App#507

Revert "Bug 92367: [SERAp Estudantes] - Aplicação no dispositivo físico está exibindo as questões com espaço entre o texto base e o enunciado."

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/gradle.properties
lib/stores/principal.store.dart
pubspec.yaml

[AB#102635](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/102635)
Aplicação não limpa os campos de login quando faz logoff.

Aplicação não limpa os campos de login quando faz logoff.

---

android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
lib/ui/views/prova/questao.view.dart

Correção Reprodução áudio na Web

---

lib/stores/principal.store.dart
lib/ui/views/login/login.view.dart

[AB#102999](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/102999)
[AB#102714](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/102714)

Correção de Erro ao Reproduzir Áudio no Tablet e Sair

---

lib/services/api_service.dart
lib/stores/prova.store.dart
lib/ui/views/tai/resumo_tai.view.dart
pubspec.yaml

[AB#104806](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/104806)

Bug 104806: [SERAp Estudantes] - Prova TAI - Ao finalizar a prova, a aplicação não move da tela 'prova atual' para 'provas anteriores'.

---

lib/main.ioc.config.dart
lib/stores/job.store.dart
lib/workers/dispacher.dart
pubspec.yaml

[AB#105681](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105681)

Bug 105681: [Estudantes] Sincronização de respostas offline não acontecendo automaticamente

---

lib/ui/views/orientacao_inicial/orientacao_inicial.view.dart
lib/ui/widgets/apresentacao/apresentacao.widget.dart
pubspec.yaml

[AB#105058](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105058)

Bug 105058: [Estudantes] A identificação de versão está se sobrepondo aos botões

---

lib/stores/resumo_tai_view.store.dart

[AB#105989](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105989)

Bug 105989: [Estudantes] Exibindo o nome de outra prova

---

lib/main.dart
lib/stores/principal.store.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/widgets/player_audio/player_audio_widget.dart
lib/utils/firebase.util.dart
lib/utils/route_observer.dart
pubspec.lock
pubspec.yaml

[AB#105933](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105933)

Bug 105933: [SERAp Estudantes] - Resumo - Audio da prova não reproduz na revisão das questões.

---

lib/ui/views/orientacao_inicial/orientacao_inicial.view.dart
lib/ui/widgets/apresentacao/apresentacao.widget.dart

[AB#105821](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105821)
[AB#105941](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105941)

Aplicação retorna para tela de prova atual quando perder a conexão

---

lib/main.dart
lib/utils/route_observer.dart
lib/workers/dispacher.dart
lib/workers/jobs/finalizar_prova_pendente.job.dart
lib/workers/jobs/sincronizar_respostas.job.dart
pubspec.yaml

[AB#105681](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105681)

Bug 105681: [SERAp Estudantes] - Sincronização de respostas offline não acontecendo automaticamente

---

pubspec.lock
pubspec.yaml

[AB#106732](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/106732)

Bug 106732: [SERAp Estudantes] Não permite responder provas após atualizar o app

---

lib/ui/views/admin/prova_resumo.admin.view.dart
lib/ui/views/admin/prova_resumo_caderno.admin.view.dart
lib/ui/views/prova/resumo_respostas.view.dart
lib/ui/views/prova_resultado/prova_resultado_resumo.view.dart
lib/ui/widgets/adaptative/adaptative.icon.button.widget.dart
pubspec.yaml

[AB#106854](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/106854)

Bug 106854: [Estudantes] Ícone de revisão não é exibido na web quando offline

---

lib/ui/views/admin/home.admin.view.dart
lib/ui/views/admin/prova_questao.admin.view.dart
lib/ui/views/home/tabs/tabs/prova_atual_tab.view.dart
lib/ui/views/home/tabs/tabs/provas_anteriores_tab.view.dart
lib/ui/views/prova/questao.view.dart
lib/ui/views/prova/questao_revisao.view.dart
lib/ui/views/prova_resultado/questao_resultado_detalhe.view.dart
lib/ui/views/tai/questao_tai.view.dart
lib/ui/views/tai/resumo_tai.view.dart
lib/ui/widgets/dialog/dialog_default.widget.dart
pubspec.yaml

[AB#106868](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/106868)

User Story 106868: [Estudantes] Exibir sempre a barra de rolagem de tela

---

lib/main.ioc.dart

[AB#105259](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/105259)

Bug 105259: [SERAp Estudantes] Requisição sendo feitas para outras APIs

---

lib/enums/request_status.enum.dart
lib/stores/prova_tai.view.store.dart
lib/stores/questao_tai_view.store.dart
lib/stores/questao_tai_view.store.g.dart
lib/stores/resumo_tai_view.store.dart
lib/ui/views/tai/questao_tai.view.dart
lib/ui/widgets/dialog/dialogs.dart

[AB#106266](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/106266)

Bug 106266: [SERAp Estudantes] - Prova TAI - Tratamento de mensagens

---

lib/stores/questao_tai_view.store.dart
pubspec.yaml

[AB#104807](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/104807)

Bug 104807: [SERAp Estudantes]  - Prova TAI - Não está armazenando tempo de resposta do aluno no banco.

---

lib/stores/prova.store.dart
lib/ui/views/prova/prova.view.dart

[AB#107842](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/107842)

Bug 107842: [SERAp Estudantes] - Erro ao continuar prova após voltar de uma prova inicializada com tempo

---

lib/ui/widgets/dialog/dialogs.dart

[AB#109256](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/109256)

Bug 109256: [SERAp Estudantes] - Alterar mensagem de remoção de provas ao fazer logout

---

lib/database/daos/prova.dao.dart
lib/dtos/prova.response.dto.dart
lib/dtos/prova.response.dto.g.dart
lib/dtos/prova_anterior.response.dto.g.dart
lib/enums/prova_status.enum.dart
lib/models/prova.model.dart
lib/models/prova.model.g.dart
lib/stores/home.store.dart
lib/stores/prova.store.dart
lib/utils/app_config.util.dart
lib/workers/jobs/finalizar_prova_pendente.job.dart
pubspec.yaml
rename_deferred_parts.dart

[AB#111428](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/111428)

User Story 111428: [Estudantes] Criar status de finalização de provas

---

pubspec.lock
pubspec.yaml

[AB#112828](https://dev.azure.com/amcomgov/c9b99f20-3b4d-464b-a2eb-69d1f704e9d3/_workitems/edit/112828)

Executado build_runner para atualizar arquivos g.dart

---

lib/stores/principal.store.dart
lib/ui/widgets/dialog/dialogs.dart
lib/workers/jobs/sincronizar_respostas.job.dart

Ajustes gerais nas sincronização

130402-ajustes-sincronizacao
